# Generated by Django 2.2.6 on 2019-10-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_course',
            name='e_result',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student_course',
            name='e_seat_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_course',
            name='e_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
